theme_advanced_toolbar_location: top
theme_advanced_toolbar_language : pl
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - fullscreen
  - textcolor
  - code
  - autolink
  - visualblocks
  - preview
  - link
  - hr
  - searchreplace
  - spellchecker
  - wordcount
  - insertdatetime
  - image
  - print
  - nonbreaking
  - media
  
toolbar: 
  - undo redo
  - indent outdent bullist numlist
  - forecolor backcolor
  - fontselect
  - fontsizeselect
      

